/** Giá trị mặc định khi owner chưa lưu cấu hình — đồng bộ với backend DEFAULT_OWNER_BOOKING_CONFIG */
export const BOOKING_LIFECYCLE_DEFAULTS = {
  allowPrebook: true,
  maxPrebookDays: 7,
  holdMinutes: 15,
  maxSlotsPerBooking: 1,
  requireDeposit: true,
  depositPercent: 30,
  allowCancel: true,
  freeCancelValue: 60,
  freeCancelUnit: "minutes",
  refundOnTimePercent: 100,
  forfeitDepositLate: true,
  allowCancelOverlap: false,
  overlapOnlyBeforeCheckin: true,
  overlapRefundPercent: 100,
  refundToWalletHours: 24,
  allowReschedule: true,
  maxRescheduleTimes: 1,
  rescheduleBeforeValue: 120,
  rescheduleBeforeUnit: "minutes",
  earlyCheckinFreeMinutes: 30,
  earlyCheckinChargeHours: 1,
  maxLateCheckinMinutes: 15,
  lateCheckinAction: "auto_cancel",
  remindBeforeCheckinMinutes: 15,
  allowLateCheckout: true,
  lateCheckoutFreeMinutes: 15,
  lateCheckoutChargePerHours: 1,
  lateCheckoutDayThresholdHours: 4,
  qrShared: true,
  qrValidInBookingWindow: true,
  qrNoReuse: true,
  qrEncryptedPerBooking: true,
  hourlySingleEntry: true,
  dailyMaxEntries: 5,
  monthlyUnlimited: true,
  notifyBookingSuccess: true,
  notifyDepositSuccess: true,
  notifyCheckinReminder: true,
  notifyHoldExpiring: true,
  notifyBookingCancelled: true,
  notifyRefundWallet: true,
  templates: {
    bookingConfirm: "Xin chào {ten_khach}, đặt chỗ {ma_dat_cho} tại {ten_bai_xe} đã được ghi nhận. Giờ vào: {gio_vao}.",
    depositSuccess: "Thanh toán cọc {so_tien} cho booking {ma_dat_cho} thành công.",
    checkinReminder: "Nhắc bạn check-in booking {ma_dat_cho} sau {phut} phút nữa tại {ten_bai_xe}.",
    cancelled: "Booking {ma_dat_cho} đã bị huỷ. {hoan_tien}",
    refund: "Đã hoàn {so_tien} về ví cho booking {ma_dat_cho}.",
    checkoutSuccess: "Check-out thành công booking {ma_dat_cho}. Cảm ơn bạn đã sử dụng dịch vụ.",
    lateFee: "Booking {ma_dat_cho} phát sinh phí trễ {so_tien}. Vui lòng thanh toán trên ứng dụng.",
  },
};
