SET FOREIGN_KEY_CHECKS=0;
DELETE FROM bookings;
DELETE FROM districts;
DELETE FROM employee_activities;
DELETE FROM owner_parking;
DELETE FROM parking_lots;
DELETE FROM parking_operational_states;
DELETE FROM parking_prices;
DELETE FROM parking_slots;
DELETE FROM payments;
DELETE FROM reviews;
DELETE FROM revoked_tokens;
DELETE FROM transactions;
DELETE FROM users;
DELETE FROM user_flags;
DELETE FROM user_vehicles;
DELETE FROM vehicles;
DELETE FROM wallet_transactions;
DELETE FROM wallets;
SET FOREIGN_KEY_CHECKS=1;
